### PR TITLE
Fixed #23 -- Added static file serving to flask

### LINKED ISSUE #23: jasmine-jquery fixtures
Hey I'm having some trouble with `jasmine-jquery` and jasmine-py. The helper works fine, but the fixtures don't at least not the once loading from filesystem.
Does anyone have any experience with that? I'll dig into the code to see why jasmine returns a 404 for the fixtures.
Cheers, joe

### PR DESCRIPTION
**Pull request by codingjoe**
Changes:
 - Changed response Content-Type guessing to use python's `mimetypes`.
 - Added `fixtures_dir` config.
 - Added generic static file serving for fixtures.

### CODE REVIEW

**Comment by codingjoe** [comment]
@Gerg I went for the second option. Tho is requires you to change the default `jasmine-jquery` `fixturePath`. I didn't want to break the current routing to get this pulled faster.

**Comment by codingjoe** [comment]
@Gerg I split my commits and resolved your political issues. Please reconsider.

**Comment by Gerg** [comment]
Merged c1c2ef35b7c929e499abf9fd085c3b71dcc5e058

**Comment by codingjoe** [comment]
@Gerg you mentioned that there is a certain way how you extend the server in ruby. Would you mind pointing me into the right code direction. I'd really like to fix this.

**Comment by Gerg** [comment]
Jasmine gem allows users to mount their own Rack applications within the Jasmine app.

The feature is documented here: http://jasmine.github.io/2.2/ruby_gem.html#section-Configuration.

Here is the implementation:
1. https://github.com/jasmine/jasmine-gem/blob/969951c57b28749be2be78c88db53192120ce309/lib/jasmine/configuration.rb#L56-L66
2. https://github.com/jasmine/jasmine-gem/blob/18669008f2af726c0759ec47b002915b79dde791/lib/jasmine/application.rb

**Comment by codingjoe** [comment]
@Gerg thanks, I'll look into it.

**Pull request closed without merging**
